spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

server.servlet.session.cookie.secure=true

app.security.admin.nombre=${ADMIN_NAME:Administrador General}
app.security.admin.username=${ADMIN_USERNAME}
app.security.admin.password=${ADMIN_PASSWORD}
app.security.admin.password-encoded=${ADMIN_PASSWORD_ENCODED:true}
app.security.admin.temp-registration-enabled=${ADMIN_TEMP_REGISTRATION_ENABLED:false}
app.security.require-https=${SECURITY_REQUIRE_HTTPS:true}

spring.thymeleaf.cache=true

server.forward-headers-strategy=framework

logging.level.com.aviatur=INFO
logging.level.org.springframework.web=WARN
logging.level.org.hibernate.SQL=WARN
