spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/sgia_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Bogota&createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:sgia_user}
spring.datasource.password=${DB_PASSWORD:sgia_password}

spring.thymeleaf.cache=false

logging.level.com.aviatur=DEBUG
logging.level.org.springframework.web=INFO
