ALTER TABLE sede
    MODIFY COLUMN nombre VARCHAR(100) NOT NULL,
    MODIFY COLUMN direccion VARCHAR(150) NOT NULL;

ALTER TABLE area
    MODIFY COLUMN nombre VARCHAR(100) NOT NULL,
    MODIFY COLUMN id_sede INT NOT NULL;

ALTER TABLE usuario_asignado
    MODIFY COLUMN nombre VARCHAR(100) NOT NULL,
    MODIFY COLUMN cedula VARCHAR(20) NOT NULL;

ALTER TABLE sistema_operativo
    MODIFY COLUMN nombre VARCHAR(50) NOT NULL,
    MODIFY COLUMN version VARCHAR(50) NOT NULL;

ALTER TABLE equipo
    MODIFY COLUMN nombre_pc VARCHAR(100) NOT NULL,
    MODIFY COLUMN tipo VARCHAR(50) NOT NULL,
    MODIFY COLUMN modelo VARCHAR(100) NULL,
    MODIFY COLUMN serial VARCHAR(100) NOT NULL,
    MODIFY COLUMN inventario VARCHAR(100) NOT NULL,
    MODIFY COLUMN procesador VARCHAR(100) NULL,
    MODIFY COLUMN ram VARCHAR(50) NULL,
    MODIFY COLUMN almacenamiento VARCHAR(50) NULL,
    MODIFY COLUMN estado ENUM('ACTIVO','DAÑADO','OBSOLETO','ACARGO') NOT NULL,
    MODIFY COLUMN id_usuario_asignado INT NULL,
    MODIFY COLUMN id_area INT NOT NULL,
    MODIFY COLUMN id_sistema_operativo INT NOT NULL;

ALTER TABLE software
    MODIFY COLUMN nombre VARCHAR(100) NOT NULL;

ALTER TABLE monitor
    MODIFY COLUMN inventario VARCHAR(100) NOT NULL,
    MODIFY COLUMN serial VARCHAR(100) NOT NULL,
    MODIFY COLUMN pulgadas DECIMAL(4,1) NOT NULL,
    MODIFY COLUMN id_equipo INT NOT NULL;

ALTER TABLE impresora
    MODIFY COLUMN serial VARCHAR(100) NOT NULL,
    MODIFY COLUMN ip VARCHAR(45) NOT NULL,
    MODIFY COLUMN direccion VARCHAR(150) NOT NULL,
    MODIFY COLUMN estado ENUM('ACTIVO','DAÑADO','OBSOLETO','ACARGO') NOT NULL,
    MODIFY COLUMN id_sede INT NOT NULL,
    MODIFY COLUMN id_area INT NULL;

ALTER TABLE telefono
    MODIFY COLUMN mac VARCHAR(50) NOT NULL,
    MODIFY COLUMN serial VARCHAR(100) NOT NULL,
    MODIFY COLUMN modelo VARCHAR(100) NULL,
    MODIFY COLUMN referencia VARCHAR(100) NULL,
    MODIFY COLUMN estado ENUM('ACTIVO','DAÑADO','OBSOLETO','ACARGO') NOT NULL,
    MODIFY COLUMN id_usuario_asignado INT NULL;

ALTER TABLE administrador
    MODIFY COLUMN nombre VARCHAR(100) NOT NULL,
    MODIFY COLUMN username VARCHAR(50) NOT NULL,
    MODIFY COLUMN password_hash VARCHAR(255) NOT NULL;

ALTER TABLE prestamo
    MODIFY COLUMN nombre_empleado VARCHAR(100) NOT NULL,
    MODIFY COLUMN cedula VARCHAR(20) NOT NULL,
    MODIFY COLUMN fecha_inicio DATETIME NOT NULL,
    MODIFY COLUMN fecha_fin DATETIME NOT NULL,
    MODIFY COLUMN fecha_devolucion DATETIME NULL,
    MODIFY COLUMN id_equipo INT NOT NULL;

ALTER TABLE historial_traslado
    MODIFY COLUMN tipo_activo ENUM('EQUIPO','IMPRESORA','TELEFONO') NOT NULL,
    MODIFY COLUMN id_activo INT NOT NULL,
    MODIFY COLUMN fecha DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN origen VARCHAR(150) NOT NULL,
    MODIFY COLUMN destino VARCHAR(150) NOT NULL;
